site_name: Effective FiveM Lua
repo_url: https://github.com/Manason/effective-fivem-lua
theme:
    name: material
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.expand
        - content.code.annotate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
    - 'index.md'
    - 'structure.md'
    - 'functions.md'
    - 'tables.md'
    - 'variables.md'
    - 'conditionals.md'
    - 'natives.md'
